language: python
python:
  - '2.7'


# Use the new container-based infrastructure. No "sudo" is possible now.
sudo: false


# Cache the .mbs folder.
cache:
  directories:
    - $HOME/.mbs
    - $HOME/.ant/lib


env:
  global:
    - secure: "MXZQNZvztG3RdrPFQceviubtCvCBeRNt/Q0KL3/4kzUU4Diy3X1p+ZZC2maBP2yz1AAm39yy2O2eKFFRfoDRVnunawPW8xfKkS//mDACBOoTjrcgDPH2pvqzbxivCz9hUw4tTXs18tKLbtK8annRlSbkoh9cZn53GwOiLTyHbuU="


install:
  - pip install -q requests


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - python mbs/mbs


#after_success:
#  -

#deploy:
#  provider: releases
#  api_key:
#    secure: hgQgH8+YKlM3v6Oak/LCg7MR+ie7CkhjfMf9tDEtfHr+qlER6lH045XMycJZwonvGatrc/QP06MEeKHEAX+ft5pJFPN/1QMhItedyRha4gjrZL7KUcy+gBNn3VClczTIy/t7Uyd/fZuOenXvngo5NfTrW5gYq9zGhrhCSCE4IFw=
#  file:
#    - 
#    - 
#  on:
#    repo: muhkuh-sys/org.muhkuh.tests-iomatrix
